### ISSUE TITLE
Name from event registration might deverge from names of existing Persons

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/member-database#42]
If I register with an existing Person's email address, I can define a different name. I think we could allow that, but in this case the adjusted name does not show up in the `/event/<id>/participats` endpoint.

**Comment by MaxNoe** [comment]
Yes, there are a few different approaches to this we should discuss which one is preferable.

As it is now, I would consider it a bug, so changing 
https://github.com/pep-dortmund/member-database/blob/c43075ea1b037745779bf6dded11f1434efa1cee/database/events/templates/participants.html#L20 should be done to something like
```
p.data.get('name', p.person.name)
```
so that if a name is given in the schema, that name is used.

Current approach:
* name is stored in `Person`, when `Person` is created.

 If a registration is done for an already existing person, that name is not updated. Name is also stored in the registration data, so that has the name associated with that event.

**Comment by bixel** [comment]
Yeah I expected something like that. I think updating the template should be fine, especially if you think of adjustments people want to make for e.g. the Absolventenfeier.

**Comment by MaxNoe** [comment]
Fixed in #49
